basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  internal_handlers.refreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  internal_handlers.signinRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_handlers.signupRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  internal_handlers.tokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact: {}
  description: Truyentan service API
  title: Truyentan API
  version: "1.0"
paths:
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: refresh request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.refreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handlers.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: Refresh token
      tags:
      - auth
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: signin request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.signinRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handlers.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: User signin
      tags:
      - auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Create new user account
      parameters:
      - description: signup request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.signupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_handlers.tokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: User signup
      tags:
      - auth
swagger: "2.0"
