name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run Go lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...
      - name: Build Go project
        run: go build ./...
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Run ESLint
        working-directory: web
        run: npm run lint
